# Nombre de la aplicación
spring.application.name=Ejercicio

# ============================
#   BASE DE DATOS H2 PERSISTENTE
# ============================

# Base H2 guardada en archivo local
spring.datasource.url=jdbc:h2:file:./data/ejercicio
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=utn
spring.datasource.password=test

# Dialecto de Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate actualiza las tablas sin borrarlas
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola H2 habilitada
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

